### ISSUE TITLE
Tasks to complete by Friday

### ISSUE THREAD

**Issue by joeylouise** [FAC10/happy#51]
**Tasks**
- [ ] Notifications view
- [x] Settings view
- [x] Upload media from phone view
- [x] Style modal view that contains memories
- [x] Add interesting animation for when modal pops up
- [ ] Add view for adding a text memory
- [x] Add tags area at top of home view
- [x] Add favicon
- [ ] Make visualisation behave better (i.e. confine to certain space?, bigger nodes?)
- [ ] Make sure it is responsive

**Stretch**
- [ ] Take photo / video page
